Repository TokTok/hs-schema, pull requests merged in 2022-02, with the labels that each got.

#37 chore: Make library visible outside the package.
  BUILD.bazel
Labels: chore

#38 chore: Run buildifier.
  BUILD.bazel
Labels: chore

#1 feat: Add enum to schema.
  src/Data/Schema.hs
Labels: enhancement

#39 chore: Use docker based CI build.
  .github/docker/Dockerfile
  .github/settings.yml
  .github/workflows/publish.yml
Labels: chore

#40 chore: Use toktok-stack image for haskell stack builds
  .github/docker/Dockerfile
Labels: chore

#41 refactor: Use new `Config` for `toObject` in msgpack-types.
  stack.yaml
  test/Data/SchemaSpec.hs
Labels: refactor

#42 chore: Add common CI workflow, currently includes buildifier.
  .github/workflows/ci.yml
Labels: chore

#43 feat: Initial version with C code generation.
  BUILD.bazel
  schema.cabal
  src/Data/Schema.hs
  src/Data/Schema/Builder.hs
  src/Data/Schema/C.hs
  src/Data/Schema/Pretty.hs
  src/Data/Schema/Type.hs
  test/Data/SchemaSpec.hs
Labels: enhancement

#45 test: Add a testcase.
  BUILD.bazel
  schema.cabal
  src/Data/Schema/Builder.hs
  src/Data/Schema/C.hs
  src/Data/Schema/Pretty.hs
  src/Data/Schema/Type.hs
  test/Data/Schema/PrettySpec.hs
  test/Data/SchemaSpec.hs
Labels: test

#47 feat: Add deinline transformation.
  schema.cabal
  src/Data/Schema/Deinline.hs
Labels: enhancement

#48 perf: Use strict data types.
  src/Data/Schema/Builder.hs
  src/Data/Schema/Type.hs
Labels: performance
